inherit_from: .rubocop_todo.yml

AllCops:
  Exclude:
    - 'db/migrate/20211010065212_devise_create_customers.rb'

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*'
    - 'db/**/*'

Metrics/MethodLength:
  Exclude:
    - 'app/helpers/notifications_helper.rb'
    - 'app/models/pet.rb'
    - 'db/**/*'
